# -*- coding: utf-8 -*-
"""class testing in python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1377hR1bgnU0W9pKTJdMACATxU_wGXr12
"""

a=
type (a)

a = 10
type(a)

#conversion of int to float
num1 = 10
num2 = 20

num3 = num1 + num2

type('favor')

'favour' .upper

student_name = input("enter name: ")
phone_number = input("enter phone number: ")
Email_address = input("enter Email address:")
Gender = input ("enter student age:")

print (f'student_name: (name)')
print (f'student_name: (name)')
print (f'student_name: (name)')
print (f'student_name: (name)')

def login_details():
  student_name = input("enter name: ")
phone_number = input("enter phone number: ")
Email_address = input("enter Email address:")
Gender = input ("enter student age:")
 return name, gender, age, phone_num, email_address

student_file = {
  #  'name' :name,
  #  'gender' :gender,
  # 'age' :age,
  # 'phone_num' :phone
  # 'mail' :email
# }



empty = []
print(type(empty))

password = input ("Enter ")

# sort a list using sort method
my_var2 = [20,10,5,17,13,8]
my_var2.sort()
print (my_var2)

my_var2.reverse()

# adding a list to a list
var1 = [1,2,3,4,5]
var2 = [6,7,8,9,10]

# appenmd method
var1.append(var2)
print(var1)

# adding a list to a list
var1 = [1,2,3,4,5]
var2 = [6,7,8,9,10]

# appenmd method
var1.append(var2)
print
print

# sort a list using sort method
my_var2 = [20,10,5,17,13,8]
sorted_list = sorted (my_var2)
print (sorted_list)
print (my_var2)

item_popped = var1.pop()
print(item_popped)
print(var1)

print(var1)
var1.remove(6)

del var1 [3]
print()

var1 = [1,2,3,6,7,8,9,10,11]

# print(var[4])

# print(var1[4:7])

print(var1[4:6])





name = "Ehis"

def change_name(loc_name):
   class_name = 'AWS'
   year =
    print(loc_name)

change_name('Osas')

for number in range(0,10,30):
    print (number)

40 to 50 = D
51 to 60 = c
61 to 75 = B
76 to 100 =A

score = input("enter student score")
print(score + 30)



score = int(input(if score >= 40 and score is <=50:
  print("student's grade is D")



my_var2

for item in bag

bag =
['spoon', 'wig', 'mirror'', ]

[19]:
#



my_var = ['Enny',100,'Bola',30.6,True,False]
print(my_var)

last_item = my_var[-1]
print(last_item)



print ("your answer is", num3)

type (num3)

#conversion of float to int
num1 = 10
num2 = 20

num3 = num1 + num2
kk k